openapi: "3.0.1"
info:
  title: Notifications Service API
  description: Notifications Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /notifications:
    get:
      tags: [Notifications]
      description: Gets the notifications
      operationId: mib.resources.notifications.notifications
      responses:
        200:
          description: Return notifications
        default:
          description: An error occured during retrieving the notifications
