"""empty message

Revision ID: 4f7030f98bf8
Revises: 
Create Date: 2021-12-08 16:16:07.960406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f7030f98bf8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id_notification", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_message", sa.Integer(), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.Column("is_notified", sa.Boolean(), nullable=True),
        sa.Column("for_recipient", sa.Boolean(), nullable=True),
        sa.Column("for_sender", sa.Boolean(), nullable=True),
        sa.Column("for_lottery", sa.Boolean(), nullable=True),
        sa.Column("from_recipient", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_notification"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    # ### end Alembic commands ###
